### ISSUE TITLE
[feature] allow QR to point to an `.setup.json` address

### ISSUE THREAD

**Issue by Merith-TK** [Epicpkmn11/dsidl#1]
basically, the thought process is that it can be used to point to an "setup.json" rather than an normal file

kinda like
```json
{
  "dsidl" : {
    "files" : [
      "/data/config.txt" : "http://example.com/data/config.txt",
      "/program.nds" : "http://example.com/data/program.nds",
    ]
  }
}
```

where it then prompts the user that this is an multi-download QR, and then were they want this data saved (select for all or for single file at an time)

**Comment by Epicpkmn11** [comment]
Added (though in a slightly different way) in e1f665b7b6bf84db881e68a6611d03ff173d36d9

What I did is put the JSON right into the QR itself as my goal in this is to a very simplistic downloader and that's simpler imo.

It supports either arrays or objects, with arrays simply being a list of URLs that it prompts the user for location/name like normal and objects allowing you to set both the URL and the output path. Examples:

```json
[
    "It'll print anything that doesn't start 'http'",
    "https://example.com",
    "http://uwu.xn--rck9c.xn--tckwe",
    "Thanks for downloading!"
]
```
![](https://cdn.discordapp.com/attachments/625519299666378753/986861045987569664/qr.png)

```json
{
    "sd:/example.html": "https://example.com",
    "": "Comments still work",
    "sd:/uwu.html": "http://uwu.xn--rck9c.xn--tckwe"
}
```

![](https://cdn.discordapp.com/attachments/625519299666378753/986861139205955614/qr.png)

**Comment by Epicpkmn11** [comment]
Added external scripts in cc5b3a42ef82d4c6ded1220c6bd334ab73e8657f, I did it a little differently as I don't particularly like relying on file extensions so to start one you put this in a QR:
```json
{"dsidl:src": "https://example.test/script.json"}
```
(`"dsidl:src"` was chosen since `:` makes it an invalid FAT path)

then the script file is:
```json
{
    "dsidl": 1,
    "script": {
        "/program.nds": "http://example.test/data/program.nds"
    }
}
```
or such, with `"dsidl"` being a version number as a sanity check and incase it changes significantly in the future and `"script"` being the same as above, an object or array.

I did `"script"` instead of `"files"` since if I add unzipping I'll probably do it with either `"sd:/file.zip": "unzip:/destination/path"` or so or maybe making the items into objects so you can specify an action like in UU, imo works better together as then they can be mixed together in any order, download unzip download unzip or so.

**Comment by Merith-TK** [comment]
Id say this is an fair compromise,

so you can have
```
{
   "/game.nds":"https://example.com/roms/game.nds",
   "dsidl:src":"https://example.com/roms/game.json",
}
```
and have game.json pont out an series of other files needed as well that may or may not update at some point?

**Comment by Merith-TK** [comment]
testing `dsidl:src` and it appears to work, however it does not prompt the user where they wish to have the file saved, and instead defaults to `sd:/`
