### ISSUE TITLE
Change parsing filename to header

### ISSUE THREAD

**Issue by awkitsune** [Epicpkmn11/dsidl#17]
I made a small program so send files to DSi using this app ([Here is repo](https://github.com/awkitsune/DSiSend)) and ran into a problem, DSi Downloader gets filename not from header but from link's end (Problem is described in repo's readme under __Bugs__ section)

**Comment by Epicpkmn11** [comment]
Hmm yeah that seems smart, if you make a PR adding it I'll probably merge it, otherwise I can give it a try sometime soon. Note that it seems not all servers set the Content-Disposition so make sure that it can fall back to parsing the link if you PR it. (Tried a couple on U-DB and [NitroHax's zip](https://www.chishm.com/NitroHax/NitroHax.zip) doesn't seem to have it)

**Comment by awkitsune** [comment]
First I need to figure out how and where exactly DSi Downloader parsing filename

**Comment by Epicpkmn11** [comment]
https://github.com/Epicpkmn11/dsidl/blob/main/arm9/source/script.cpp#L18-L31

It does that before the download so it'll require a bit of reworking to be able to get the headers first, might be best to just do a HEAD request, have the user check the file name, then do the actual download.

**Comment by awkitsune** [comment]
Actually a good way, I will try to figure it out and make a pull request

**Comment by awkitsune** [comment]
No chances of me doing it, my C knowledge is so poor

**Comment by awkitsune** [comment]
Now my program doing both filename in link and in header, so issue is closed
